[package]
name = "bevy_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# bevy deps
bevy = "0.7"
bevy-inspector-egui = "0.11.0"
bevy_asset_loader = { version = "0.11.0", features = ["stageless"] }
iyes_loopless = "0.5.1"

[target.'cfg(target_arch = "wasm")'.dependencies]
# Nothing

[target.'cfg(target_arch = "x86_64")'.dependencies]
bevy_framepace = "0.4.0"
