[package]
name = "bevy_ecs_tilemap_cpu_anim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Bevy deps
bevy = "0.7"
bevy_ecs_tilemap = "0.6.0"
