name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-build-stable-${{ hashFiles('**/Cargo.toml') }}
      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
        if: runner.os == 'linux'
      - name: Build
        run: cargo build

#  build-wasm:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#      - name: Pull build cache
#        id: cache-build
#        uses: actions/cache@v3
#        with:
#          path: ./launchers/wasm/dist
#          key: wasm-${{ hashFiles('Cargo.lock') }}-${{ hashFiles('./src') }}-${{ hashFiles('./launchers') }}
#      - name: Install Trunk
#        if: steps.cache-build.outputs.cache-hit != 'true'
#        uses: jetli/trunk-action@v0.1.0
#        with:
#          version: "latest"
#      - name: Trunk Build
#        if: steps.cache-build.outputs.cache-hit != 'true'
#        run: trunk build
