name: CI

on:
  push:
    branches: [main]

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install alsa and udev
        run: sudo apt-get update --fix-missing; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
        if: runner.os == 'linux'

      # Run clippy
      - name: Test
        run: cargo clippy -- -D warnings
