name: Build desktop releases
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release-linux:
    runs-on: ubuntu-latest
    name: Build the linux release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - name: Call the build
        run: cargo build --release && mv ./target/release/bevy_game ./ && mv ./bevy_game/assets ./
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: assets
